name: build-test
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: "bash"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Run build & publish script"
        run: ./publish.sh
