name: publish-docker
on:
  release:
    types: [published]

defaults:
  run:
    shell: "bash"

jobs:
  publish-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: "Echo current version number"
        run: echo "Current version is ${{ github.event.release.tag_name }}"

      - name: "Run publish docker script"
        run: ./publish-docker.sh ${{ github.event.release.tag_name }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push image to Docker Hub"
        run: ./push-docker.sh ${{ github.event.release.tag_name }} alisaqaq

      - name: "Login to Tencent Cloud TCR"
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          password: ${{ secrets.TENCENT_CLOUD_TOKEN }}

      - name: "Push image to Tencent Cloud TCR"
        run: ./push-docker.sh ${{ github.event.release.tag_name }} ccr.ccs.tencentyun.com/alisaqaq
